# Generated by Django 5.2.3 on 2025-06-21 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("price_usd", models.IntegerField()),
                ("odometer", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("image_url", models.URLField(max_length=255, unique=True)),
                ("images_count", models.IntegerField()),
                ("car_number", models.CharField(max_length=20, unique=True)),
                ("car_vin", models.CharField(max_length=255)),
                ("datetime_found", models.DateTimeField()),
            ],
        ),
    ]
