# Generated by Django 5.2.3 on 2025-06-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="car_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="auto",
            name="datetime_found",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="auto",
            unique_together={("car_number", "car_vin")},
        ),
    ]
